version: "2.3"

services:
  db-service:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_MULTIPLE_DATABASES: "app,keycloak"
      POSTGRES_PASSWORD: shashank
    mem_limit: 512M
    volumes:
      - "./db-service/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./db-service/data:/var/lib/postgresql/data"
  keycloak-auth-service:
    image: jboss/keycloak
    ports:
      - "8080:8080"
    depends_on:
      - db-service
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-service
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: shashank
      DB_SCHEMA: public
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: testing
      JAVA_OPTS: -server -Xms256m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=128M -XX:+UseAdaptiveSizePolicy -XX:MaxMetaspaceSize=512m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true-Djava.net.preferIPv4Stack=true
    mem_limit: 1024M

  discovery-server:
    build:
      context: .
      dockerfile: discovery-server/Dockerfile
    ports:
      - "7070:7070"
    depends_on:
      - db-service
    entrypoint: "./wait-until-start -t 240 keycloak-auth-service:8080 -- java -jar /app.jar"
    environment:
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
    mem_limit: 300M

  account-service:
    build:
      context: .
      dockerfile: account-service/Dockerfile
    expose:
      - "8080"
    depends_on:
      - discovery-server
      - transaction-service
    entrypoint: "./wait-until-start -t 240 discovery-server:7070 -- java -jar /app.jar"
    environment:
      TRANSACTION_SERVICE_URL: http://transaction-service
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      AUTH-SERVER_HOSTNAME: keycloak-auth-service
      AUTH-SERVER_PORT: 8080
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    mem_limit: 300M

  deposit-service:
    build:
      context: .
      dockerfile: deposit-service/Dockerfile
    expose:
      - "8081"
    depends_on:
      - discovery-server
      - transaction-service
    entrypoint: "./wait-until-start -t 240 discovery-server:7070 -- java -jar /app.jar"
    environment:
      TRANSACTION_SERVICE_URL: http://transaction-service
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      AUTH-SERVER_HOSTNAME: keycloak-auth-service
      AUTH-SERVER_PORT: 8080
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    mem_limit: 300M

  transaction-service:
    build:
      context: .
      dockerfile: transaction-service/Dockerfile
    expose:
      - "9090"
    depends_on:
      - discovery-server
      - db-service
    entrypoint: "./wait-until-start -t 240 discovery-server:7070 -- java -jar /app.jar"
    environment:
      DB_HOST: db-service
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWD: shashank
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    mem_limit: 300M

  transfer-service:
    build:
      context: .
      dockerfile: transfer-service/Dockerfile
    expose:
      - "8082"
    depends_on:
      - discovery-server
      - transaction-service
    entrypoint: "./wait-until-start -t 240 discovery-server:7070 -- java -jar /app.jar"
    environment:
      TRANSACTION_SERVICE_URL: http://transaction-service
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      AUTH-SERVER_HOSTNAME: keycloak-auth-service
      AUTH-SERVER_PORT: 8080
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    mem_limit: 300M

  withdraw-service:
    build:
      context: .
      dockerfile: withdraw-service/Dockerfile
    expose:
      - "8083"
    depends_on:
      - discovery-server
      - transaction-service
    entrypoint: "./wait-until-start -t 240 discovery-server:7070 -- java -jar /app.jar"
    environment:
      TRANSACTION_SERVICE_URL: http://transaction-service
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      AUTH-SERVER_HOSTNAME: keycloak-auth-service
      AUTH-SERVER_PORT: 8080
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
    mem_limit: 300M

  service-gateway:
    build:
      context: .
      dockerfile: service-gateway/Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - discovery-server
      - keycloak-auth-service
    entrypoint: "./wait-until-start -t 240 keycloak-auth-service:8080 -- java -jar /app.jar"
    environment:
      DISCOVERY-SERVER_HOSTNAME: discovery-server
      DISCOVERY-SERVER_PORT: 7070
      AUTH-SERVER_HOSTNAME: keycloak-auth-service
      AUTH-SERVER_PORT: 8080
      ZIPKIN_HOST: zipkin
      ZIPKIN_PORT: 9411
      S3_HOST: s3
      S3_PORT: 9000
      S3_STATIC_BUCKET: test-bucket
      S3_ACCESS_KEY: access-key
      S3_SECRET_KEY: secret-key
      S3_REGION: us-east-1

    mem_limit: 512M

  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/:/etc/prometheus/"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    depends_on:
      - service-gateway
    mem_limit: 256M

  grafana:
    image: grafana/grafana
    volumes:
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
      - "./grafana/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml"
      - "./grafana/dashboards:/etc/grafana/provisioning/dashboards/dashboards"
      - "./grafana/dashboards:/var/lib/grafana/dashboards"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    mem_limit: 256M

  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    mem_limit: 512M

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    mem_limit: 2g

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    volumes:
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx1g -Xms1g"
    depends_on:
      - elasticsearch
    mem_limit: 2g

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    volumes:
      - ./kibana/config/:/usr/share/kibana/config
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    mem_limit: 2g

  s3:
    image: minio/minio
    entrypoint: sh
    command: -c '/usr/bin/minio server /minio-data'
    environment:
      - MINIO_ACCESS_KEY=access-key
      - MINIO_SECRET_KEY=secret-key
    ports:
      - "4000:9000"
    restart: on-failure
    volumes:
      - ./minio-data:/minio-data
    mem_limit: 256M
