server:
  port: 9090

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  codec:
    max-in-memory-size: 1MB
  application:
    name: transaction-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${discovery-server.hostname}:${discovery-server.port}/eureka/
  instance:
    appName: transaction-service
    preferIpAddress: true
    hostName: transaction-service

logging:
  level:
    org:
      springframework:
        data:
          r2dbc=DEBUG:
