server:
  port: 9090

spring:
  boot:
    admin:
      client:
        url: http://${admin.hostname}:${admin.port}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  codec:
    max-in-memory-size: 1MB
  application:
    name: transaction-service
  logstash:
    server: ${logstash.hostname}
    port: ${logstash.port}
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  sleuth:
    sampler:
      probability: 100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${discovery-server.hostname}:${discovery-server.port}/eureka/
  instance:
    appName: transaction-service
    preferIpAddress: true
    hostName: transaction-service

logging:
  level:
    org:
      springframework:
        data:
          r2dbc=DEBUG:
