server:
  port: 8082

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  codec:
    max-in-memory-size: 1MB
  application:
    name: transfer-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${auth-server.hostname}:${auth-server.port}/auth/realms/service-gateway-realm/protocol/openid-connect/certs
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${discovery-server.hostname}:${discovery-server.port}/eureka/
  instance:
    appName: transfer-service
    preferIpAddress: true
    hostName: transfer-service

logging:
  level:
    root: DEBUG
    org:
      springframework:
        http.server.reactive: DEBUG
        web.reactive: DEBUG
