server:
  port: 8082

spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  codec:
    max-in-memory-size: 1MB
  application:
    name: transfer-service
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${discovery-server.hostname}:${discovery-server.port}/eureka/
  instance:
    appName: transfer-service
    preferIpAddress: true
    hostName: transfer-service
