server:
  port: 8083

spring:
  boot:
    admin:
      client:
        url: http://${admin.hostname}:${admin.port}
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  codec:
    max-in-memory-size: 1MB
  application:
    name: withdraw-service
  logstash:
    server: ${logstash.hostname}
    port: ${logstash.port}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${auth-server.hostname}:${auth-server.port}/auth/realms/service-gateway-realm/protocol/openid-connect/certs
  zipkin:
    base-url: http://${zipkin.host:localhost}:${zipkin.port:9411}/
  sleuth:
    sampler:
      probability: 100
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${discovery-server.hostname}:${discovery-server.port}/eureka/
  instance:
    appName: withdraw-service
    preferIpAddress: true
    hostName: withdraw-service

logging:
  level:
    root: DEBUG
    org:
      springframework:
        http.server.reactive: DEBUG
        web.reactive: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
